name: zRDP

on: workflow_dispatch

jobs:
  zRDP:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Pripremanje VM-a
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/zuuks/zrdp/main/Files/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/zuuks/zrdp/main/Files/nssm.exe -OutFile nssm.exe

        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Autentikacija sa NGROK nalogom   
      run: |
          .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Pokretanje NGROK-a
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/zuuks/zrdp/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/zuuks/zrdp/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/zuuks/zrdp/main/Files/loop.bat -OutFile loop.bat

        start NGROK-US.bat

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        sc start ngrok
    - name: Uspesno pokrenuta VM. Maksimalno vreme koriscenja = 6h
      run: |
        cmd /c NGROK-CHECK.bat
        cmd /c loop.bat

